language: php

dist: trusty

sudo: required

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
    include:
        - php: 5.3
          node_js: 9
          dist: precise

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - npm -v
  - node -v

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml

after_script:
  - vendor/bin/test-reporter --coverage-report coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
    code_climate:
        repo_token: a4f84c56f6bbbd5e6525fbd2798abab8add65a318084e929c30b02e8d8531a47
